#include "esp_server.h"
#include "esphome/core/log.h"
#include "esphome/components/json/json_util.h"
#include "esphome/core/application.h"
#include "esphome/core/controller_registry.h"

#ifdef USE_ESP32
#include <esp_heap_caps.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#endif

#ifdef USE_UDPSERVER
#include "esphome/components/udp_server/udp_server.h"
#endif
#ifdef USE_STORAGE
#include "esphome/components/storage/store.h"
#endif
#ifdef USE_LIGHT
#include "esphome/components/light/light_state.h"
#include "esphome/components/light/light_json_schema.h"
#endif
#ifdef USE_CLIMATE
#include "esphome/components/climate/climate.h"
#endif

// Declare constants in global namespace as they are generated by __init__.py
#if USE_ESP_SERVER_VERSION >= 2
extern const uint8_t ESPHOME_ESP_SERVER_INDEX_HTML[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_INDEX_HTML_SIZE;
#endif

#ifdef USE_ESP_SERVER_CSS_INCLUDE
extern const uint8_t ESPHOME_ESP_SERVER_CSS_INCLUDE[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE;
#endif

#ifdef USE_ESP_SERVER_JS_INCLUDE
extern const uint8_t ESPHOME_ESP_SERVER_JS_INCLUDE[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE;
#endif

namespace esphome {
namespace web_server {

static const char *const TAG = "esp_server";

static std::string strip_ansi_colors(const std::string &str) {
  std::string result;
  result.reserve(str.size());
  bool in_escape = false;
  for (size_t i = 0; i < str.size(); i++) {
    if (str[i] == '\033') {
      in_escape = true;
      continue;
    }
    if (in_escape) {
      if (str[i] == 'm')
        in_escape = false;
      continue;
    }
    result += str[i];
  }
  return result;
}

EspServer *global_esp_server = nullptr;

#ifdef USE_ESP32
static uint32_t diag_heap_free() { return heap_caps_get_free_size(MALLOC_CAP_8BIT); }
static uint32_t diag_heap_largest() { return heap_caps_get_largest_free_block(MALLOC_CAP_8BIT); }
static uint32_t diag_heap_min_free() { return heap_caps_get_minimum_free_size(MALLOC_CAP_8BIT); }
#else
static uint32_t diag_heap_free() { return 0; }
static uint32_t diag_heap_largest() { return 0; }
static uint32_t diag_heap_min_free() { return 0; }
#endif

// Constructor with initialization list
#ifdef USE_ESP32
EspServer::EspServer(web_server_base::WebServerBase *base) : base_(base), events_("/esp/events") { 
  global_esp_server = this; 
}
#else
EspServer::EspServer(web_server_base::WebServerBase *base) : base_(base) { 
}
#endif

void EspServer::setup() {
  ControllerRegistry::register_controller(this);
  global_esp_server = this;
  this->base_->add_handler(this);

#ifdef USE_ESP32
  this->events_.onConnect([this](::esphome::web_server_idf::AsyncEventSourceClient *client) {
    auto uptime = static_cast<uint32_t>(millis_64() / 1000);
    char buf[128];
    snprintf(buf, sizeof(buf), "{\"title\":\"%s\",\"comment\":\"\",\"ota\":true,\"log\":true,\"lang\":\"en\",\"uptime\":%u}",
             App.get_friendly_name().empty() ? App.get_name().c_str() : App.get_friendly_name().c_str(),
             uptime);
    client->try_send_nodefer(buf, "ping", millis(), 30000);

    // Start throttled synchronization for all entities
    this->begin(this->include_internal_);
  });
  this->base_->add_handler(&this->events_);
#endif
  this->setup_interval();
}

void EspServer::loop() {
#ifdef USE_ESP32
  this->events_.loop();
  this->advance();
#endif
}

void EspServer::setup_interval() {
  this->set_interval(30000, [this]() {
#ifdef USE_ESP32
    const auto clients = this->events_.count();
#else
    const auto clients = 0;
#endif
    if (clients == 0)
      return;
    ESP_LOGD(TAG, "diag: sse=%zu heap=%" PRIu32 " largest=%" PRIu32 " min=%" PRIu32,
             clients, diag_heap_free(), diag_heap_largest(), diag_heap_min_free());
  });

#ifdef USE_LOGGER
  if (logger::global_logger != nullptr && this->expose_log_) {
    logger::global_logger->add_log_callback(
        this, [](void *self, uint8_t level, const char *tag, const char *message, size_t message_len) {
          static_cast<EspServer *>(self)->on_log(level, tag, message, message_len);
        });
  }
#endif

#ifdef USE_UDPSERVER
  if (udp_server::udpServer != nullptr) {
    udp_server::udpServer->add_on_neighbor_callback([this](udp_server::DeviceItem *deviceItem) {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(deviceItem->toEventMessage().c_str(), "neighbor");
#endif
    });
    udp_server::udpServer->add_on_control_callback([this](udp_server::PacketControl packet) {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(udp_server::packetControlToJsonStr(packet).c_str(), "udp_control");
#endif
    });
    udp_server::udpServer->add_on_status_callback([this](udp_server::PacketStatus packet) {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(udp_server::packetStatusToJsonStr(packet).c_str(), "udp_status");
#endif
    });
    udp_server::udpServer->add_on_identity_callback([this](udp_server::PacketIdentity packet) {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(udp_server::packetIdentityToJsonStr(packet).c_str(), "udp_identity");
#endif
    });
  }
#endif

#ifdef USE_STORAGE
  if (storage::store != nullptr) {
    storage::store->add_on_situation_change([this]() {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(storage::store->global->situationToJsonStr().c_str(), "situation");
#endif
    });
  }
#endif
}

void EspServer::dump_config() { ESP_LOGCONFIG(TAG, "EspServer Addon:"); }

float EspServer::get_setup_priority() const { return setup_priority::WIFI - 1.0f; }

#ifdef USE_SENSOR
#endif

bool EspServer::canHandle(WebServerRequest *request) const {
#ifdef USE_ESP32
  char url_buf[WebServerRequest::URL_BUF_SIZE];
  String url = request->url_to(url_buf).c_str();
#else
  auto url = request->url();
#endif
  
  if (url == "/esp") return true;
  if (url.startsWith("/esp/")) return true;
  if (url == "/0.css" || url == "/0.js") return true;

  return false;
}

void EspServer::handleRequest(WebServerRequest *request) {
#ifdef USE_ESP32
  char url_buf[WebServerRequest::URL_BUF_SIZE];
  String url = request->url_to(url_buf).c_str();
#else
  auto url = request->url();
#endif

  if (url == "/esp" || url == "/esp/") {
    this->handle_index_request(request);
    return;
  }

  if (url.startsWith("/esp/")) {
    String sub_url = url.substring(4); // Keep the leading slash: "/switch/..."
    
    if (sub_url == "/events") {
      this->events_.handleRequest(request);
      return;
    }
    
    // Simple segment parser for /domain/id[/method]
    int first_slash = sub_url.indexOf('/', 1);
    if (first_slash != -1) {
      ::esphome::UrlMatch match{};
      match.domain = StringRef(sub_url.c_str() + 1, first_slash - 1);
      
      int second_slash = sub_url.indexOf('/', first_slash + 1);
      if (second_slash != -1) {
        match.id = StringRef(sub_url.c_str() + first_slash + 1, second_slash - first_slash - 1);
        match.method = StringRef(sub_url.c_str() + second_slash + 1, sub_url.length() - second_slash - 1);
      } else {
        match.id = StringRef(sub_url.c_str() + first_slash + 1, sub_url.length() - first_slash - 1);
      }
      match.valid = true;

#define HANDLE_DOMAIN(domain_str, handle_method) \
      if (match.domain == domain_str) { \
        this->handle_method(request, match); \
        return; \
      }

#ifdef USE_SENSOR
      HANDLE_DOMAIN("sensor", handle_sensor_request)
#endif
#ifdef USE_SWITCH
      HANDLE_DOMAIN("switch", handle_switch_request)
#endif
#ifdef USE_BUTTON
      HANDLE_DOMAIN("button", handle_button_request)
#endif
#ifdef USE_BINARY_SENSOR
      HANDLE_DOMAIN("binary_sensor", handle_binary_sensor_request)
#endif
#ifdef USE_FAN
      HANDLE_DOMAIN("fan", handle_fan_request)
#endif
#ifdef USE_LIGHT
      HANDLE_DOMAIN("light", handle_light_request)
#endif
#ifdef USE_TEXT_SENSOR
      HANDLE_DOMAIN("text_sensor", handle_text_sensor_request)
#endif
#ifdef USE_COVER
      HANDLE_DOMAIN("cover", handle_cover_request)
#endif
#ifdef USE_NUMBER
      HANDLE_DOMAIN("number", handle_number_request)
#endif
#ifdef USE_SELECT
      HANDLE_DOMAIN("select", handle_select_request)
#endif
#ifdef USE_LOCK
      HANDLE_DOMAIN("lock", handle_lock_request)
#endif
#ifdef USE_CLIMATE
      HANDLE_DOMAIN("climate", handle_climate_request)
#endif
#undef HANDLE_DOMAIN
    }
  }

  if (url == "/esp/diag") {
    std::string data = json::build_json([this](JsonObject root) {
      root["uptime_ms"] = millis();
#ifdef USE_ESP32
      root["sse_clients"] = this->events_.count();
#endif
      root["heap_free"] = diag_heap_free();
      root["heap_largest"] = diag_heap_largest();
      root["heap_min_free"] = diag_heap_min_free();
    });
    request->send(200, "application/json", data.c_str());
    return;
  }

  if (url == "/esp/close-events") {
    this->close_event_sources("manual /esp/close-events");
    request->send(200, "application/json", "{\"ok\":true}");
    return;
  }

#ifdef USE_ESP_SERVER_CSS_INCLUDE
  if (url == "/0.css") {
#ifdef USE_ESP32
    request->send(request->beginResponse(200, "text/css", ESPHOME_ESP_SERVER_CSS_INCLUDE, ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE));
#else
    request->send(200, "text/css", (const uint8_t*)ESPHOME_ESP_SERVER_CSS_INCLUDE, ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE);
#endif
    return;
  }
#endif

#ifdef USE_ESP_SERVER_JS_INCLUDE
  if (url == "/0.js") {
#ifdef USE_ESP32
    request->send(request->beginResponse(200, "application/javascript", ESPHOME_ESP_SERVER_JS_INCLUDE, ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE));
#else
    request->send(200, "application/javascript", (const uint8_t*)ESPHOME_ESP_SERVER_JS_INCLUDE, ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE);
#endif
    return;
  }
#endif
}

void EspServer::handle_index_request(WebServerRequest *request) {
#if USE_ESP_SERVER_VERSION >= 2
#ifdef USE_ESP32
  request->send(request->beginResponse(200, "text/html", ESPHOME_ESP_SERVER_INDEX_HTML, ESPHOME_ESP_SERVER_INDEX_HTML_SIZE));
#else
  request->send(200, "text/html", (const uint8_t*)ESPHOME_ESP_SERVER_INDEX_HTML, ESPHOME_ESP_SERVER_INDEX_HTML_SIZE);
#endif
#else
  request->send(200, "text/html", "v1 index not implemented in addon");
#endif
}

void EspServer::close_event_sources(const char *reason) {
  this->events_.close_all(reason);
}

#ifdef USE_LOGGER
void EspServer::on_log(uint8_t level, const char *tag, const char *message, size_t message_len) {
#ifdef USE_ESP32
  if (this->events_.count() == 0)
    return;
  // Official ESPHome v3 dashboard expects raw message strings for logs
  // Strip ANSI color codes to keep the UI clean
  this->events_.try_send_nodefer(strip_ansi_colors(message).c_str(), "log", millis());
#endif
}
#endif

#ifdef USE_SENSOR
void EspServer::on_sensor_update(sensor::Sensor *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->sensor_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_BINARY_SENSOR
void EspServer::on_binary_sensor_update(binary_sensor::BinarySensor *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->binary_sensor_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_SWITCH
void EspServer::on_switch_update(switch_::Switch *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->switch_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_TEXT_SENSOR
void EspServer::on_text_sensor_update(text_sensor::TextSensor *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->text_sensor_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_LIGHT
void EspServer::on_light_update(light::LightState *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->light_json_(obj).c_str(), "state", millis());
}
#endif
#ifdef USE_FAN
void EspServer::on_fan_update(fan::Fan *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->fan_json_(obj).c_str(), "state", millis());
}
#endif
#ifdef USE_COVER
void EspServer::on_cover_update(cover::Cover *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->cover_json_(obj).c_str(), "state", millis());
}
#endif
#ifdef USE_NUMBER
void EspServer::on_number_update(number::Number *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->number_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_SELECT
void EspServer::on_select_update(select::Select *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->select_json_(obj, obj->current_option()).c_str(), "state", millis());
}
#endif
#ifdef USE_CLIMATE
void EspServer::on_climate_update(climate::Climate *obj) {
  if (this->events_.count() == 0) return;
  this->events_.try_send_nodefer(this->climate_json_(obj).c_str(), "state", millis());
}
#endif

#ifdef USE_BUTTON
void EspServer::handle_button_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_buttons()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      if (match.method == "press") obj->press();
      auto json = this->button_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_FAN
void EspServer::handle_fan_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_fans()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      auto call = obj->make_call();
      if (match.method == "toggle") call.set_state(!obj->state);
      else if (match.method == "turn_on") call.set_state(true);
      else if (match.method == "turn_off") call.set_state(false);
      
      if (request->hasParam("speed")) {
        auto speed = request->getParam("speed")->value();
        call.set_speed(speed.c_str());
      }
      if (request->hasParam("oscillation")) {
        call.set_oscillating(request->getParam("oscillation")->value() == "true");
      }
      call.perform();
      auto json = this->fan_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_LIGHT
void EspServer::handle_light_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_lights()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      auto call = obj->make_call();
      if (match.method == "toggle") call.set_state(!obj->remote_values.is_on());
      else if (match.method == "turn_on") call.set_state(true);
      else if (match.method == "turn_off") call.set_state(false);
      
      if (request->hasParam("brightness")) call.set_brightness(atof(request->getParam("brightness")->value().c_str()));
      if (request->hasParam("color_brightness")) call.set_color_brightness(atof(request->getParam("color_brightness")->value().c_str()));
      if (request->hasParam("r")) call.set_red(atof(request->getParam("r")->value().c_str()));
      if (request->hasParam("red")) call.set_red(atof(request->getParam("red")->value().c_str()));
      if (request->hasParam("g")) call.set_green(atof(request->getParam("g")->value().c_str()));
      if (request->hasParam("green")) call.set_green(atof(request->getParam("green")->value().c_str()));
      if (request->hasParam("b")) call.set_blue(atof(request->getParam("b")->value().c_str()));
      if (request->hasParam("blue")) call.set_blue(atof(request->getParam("blue")->value().c_str()));
      if (request->hasParam("white_brightness")) call.set_color_brightness(atof(request->getParam("white_brightness")->value().c_str()));
      if (request->hasParam("color_temp")) call.set_color_temperature(atof(request->getParam("color_temp")->value().c_str()));
      if (request->hasParam("effect")) call.set_effect(request->getParam("effect")->value().c_str());
      
      call.perform();
      auto json = this->light_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_COVER
void EspServer::handle_cover_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_covers()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      if (match.method == "open") obj->open();
      else if (match.method == "close") obj->close();
      else if (match.method == "stop") obj->stop();
      else if (request->hasParam("pos")) obj->make_call().set_position(atof(request->getParam("pos")->value().c_str())).perform();
      
      auto json = this->cover_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_NUMBER
void EspServer::handle_number_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_numbers()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      if (request->hasParam("value")) obj->make_call().set_value(atof(request->getParam("value")->value().c_str())).perform();
      auto json = this->number_json_(obj, obj->state);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_SELECT
void EspServer::handle_select_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_selects()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      if (request->hasParam("option")) obj->make_call().set_option(request->getParam("option")->value().c_str()).perform();
      auto json = this->select_json_(obj, obj->current_option());
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_LOCK
void EspServer::handle_lock_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_locks()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      if (match.method == "lock") obj->lock();
      else if (match.method == "unlock") obj->unlock();
      else if (match.method == "open") obj->open();

      auto json = this->lock_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_CLIMATE
void EspServer::handle_climate_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_climates()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      auto call = obj->make_call();
      if (request->hasParam("mode")) call.set_mode(request->getParam("mode")->value().c_str());
      if (request->hasParam("target_temperature")) call.set_target_temperature(atof(request->getParam("target_temperature")->value().c_str()));
      if (request->hasParam("fan_mode")) call.set_fan_mode(request->getParam("fan_mode")->value().c_str());
      if (request->hasParam("swing_mode")) call.set_swing_mode(request->getParam("swing_mode")->value().c_str());
      call.perform();

      auto json = this->climate_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_SENSOR
std::string EspServer::sensor_json_(sensor::Sensor *obj, float value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "sensor-" + std::string(id_buf);
    
    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
      if (!obj->get_unit_of_measurement_ref().empty())
        root["uom"] = obj->get_unit_of_measurement_ref();
    }

    if (std::isnan(value)) {
      root["state"] = "NA";
    } else {
      char val_buf[64];
      value_accuracy_to_buf(val_buf, value, obj->get_accuracy_decimals());
      std::string state = std::string(val_buf);
      if (!obj->get_unit_of_measurement_ref().empty())
        state += " " + obj->get_unit_of_measurement_ref();
      root["state"] = state;
    }
    root["value"] = value;
  });
}
#endif

#ifdef USE_BINARY_SENSOR
std::string EspServer::binary_sensor_json_(binary_sensor::BinarySensor *obj, bool value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "binary_sensor-" + std::string(id_buf);

    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
    }

    root["state"] = value ? "ON" : "OFF";
    root["value"] = value;
  });
}
#endif

#ifdef USE_SWITCH
std::string EspServer::switch_json_(switch_::Switch *obj, bool value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "switch-" + std::string(id_buf);

    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
    }

    root["state"] = value ? "ON" : "OFF";
    root["value"] = value;
  });
}
#endif

#ifdef USE_LIGHT
std::string EspServer::light_json_(light::LightState *obj, bool include_metadata) {
  return json::build_json([this, obj, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "light-" + std::string(id_buf);
    root["state"] = obj->remote_values.is_on() ? "ON" : "OFF";
    light::LightJSONSchema::dump_json(*obj, root);

    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
      JsonArray opt = root["effects"].to<JsonArray>();
      opt.add("None");
      for (auto const &option : obj->get_effects()) {
        opt.add(option->get_name());
      }
    }
  });
}
#endif

#ifdef USE_FAN
std::string EspServer::fan_json_(fan::Fan *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "fan-" + std::string(id_buf);
    root["state"] = obj->state ? "ON" : "OFF";
    root["speed"] = (int)obj->speed;
    if (obj->get_traits().supports_oscillation())
      root["oscillation"] = obj->oscillating;

    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
    }
  });
}
#endif

#ifdef USE_COVER
std::string EspServer::cover_json_(cover::Cover *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "cover-" + std::string(id_buf);
    root["state"] = obj->is_fully_closed() ? "CLOSED" : "OPEN";
    root["position"] = obj->position;
    if (obj->get_traits().get_supports_tilt())
      root["tilt"] = obj->tilt;

    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
    }
  });
}
#endif

#ifdef USE_NUMBER
std::string EspServer::number_json_(number::Number *obj, float value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "number-" + std::string(id_buf);
    root["state"] = value;
    root["value"] = value;
    root["min"] = obj->traits.get_min_value();
    root["max"] = obj->traits.get_max_value();
    root["step"] = obj->traits.get_step();

    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
      if (!obj->get_unit_of_measurement_ref().empty())
        root["uom"] = obj->get_unit_of_measurement_ref();
    }
  });
}
#endif

#ifdef USE_BUTTON
std::string EspServer::button_json_(button::Button *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "button-" + std::string(id_buf);
    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
    }
  });
}
#endif

#ifdef USE_SELECT
std::string EspServer::select_json_(select::Select *obj, const std::string &value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "select-" + std::string(id_buf);
    root["state"] = value;
    root["value"] = value;
    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
      JsonArray options = root["options"].to<JsonArray>();
      for (auto const &option : obj->traits.get_options()) {
        options.add(option);
      }
    }
  });
}
#endif

#ifdef USE_TEXT_SENSOR
std::string EspServer::text_sensor_json_(text_sensor::TextSensor *obj, const std::string &value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "text_sensor-" + std::string(id_buf);

    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
    }

    root["state"] = value;
    root["value"] = value;
  });
}
#endif

#ifdef USE_CLIMATE
std::string EspServer::climate_json_(climate::Climate *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "climate-" + std::string(id_buf);
    root["state"] = climate::climate_mode_to_string(obj->mode);
    root["mode"] = climate::climate_mode_to_string(obj->mode);
    root["current_temperature"] = obj->current_temperature;
    root["target_temperature"] = obj->target_temperature;
    if (obj->get_traits().get_supports_two_point_target_temperature()) {
      root["target_temperature_low"] = obj->target_temperature_low;
      root["target_temperature_high"] = obj->target_temperature_high;
    }
    if (obj->get_traits().get_supports_fan_modes())
      root["fan_mode"] = climate::climate_fan_mode_to_string(obj->fan_mode);
    if (obj->get_traits().get_supports_swing_modes())
      root["swing_mode"] = climate::climate_swing_mode_to_string(obj->swing_mode);
    if (obj->get_traits().get_supports_presets())
      root["preset"] = climate::climate_preset_to_string(obj->preset.value_or(climate::CLIMATE_PRESET_NONE));
    if (obj->get_traits().get_supports_action())
      root["action"] = climate::climate_action_to_string(obj->action);

    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
      
      auto traits = obj->get_traits();
      JsonArray modes = root.createNestedArray("modes");
      for (auto mode : traits.get_supported_modes())
        modes.add(climate::climate_mode_to_string(mode));
      
      if (traits.get_supports_fan_modes()) {
        JsonArray fan_modes = root.createNestedArray("fan_modes");
        for (auto fan_mode : traits.get_supported_fan_modes())
          fan_modes.add(climate::climate_fan_mode_to_string(fan_mode));
      }
      if (traits.get_supports_swing_modes()) {
        JsonArray swing_modes = root.createNestedArray("swing_modes");
        for (auto swing_mode : traits.get_supported_swing_modes())
          swing_modes.add(climate::climate_swing_mode_to_string(swing_mode));
      }
    }
  });
}
#endif

#ifdef USE_LOCK
std::string EspServer::lock_json_(lock::Lock *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    char id_buf[128];
    obj->get_object_id_to(id_buf);
    root["id"] = "lock-" + std::string(id_buf);
    root["state"] = lock::lock_state_to_string(obj->state);
    
    if (include_metadata) {
      root["name"] = obj->get_name();
      char icon_buf[64];
      root["icon"] = obj->get_icon_to(icon_buf);
      root["entity_category"] = (int)obj->get_entity_category();
    }
  });
}
#endif

#ifdef USE_SENSOR
void EspServer::handle_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_sensors()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      bool detail_all = false;
      auto *param = request->getParam("detail");
      if (param != nullptr && param->value() == "all")
        detail_all = true;
      auto json = this->sensor_json_(obj, obj->state, detail_all);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_SWITCH
void EspServer::handle_switch_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_switches()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      if (match.method == "toggle") obj->toggle();
      else if (match.method == "turn_on") obj->turn_on();
      else if (match.method == "turn_off") obj->turn_off();
      
      auto json = this->switch_json_(obj, obj->state);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_BINARY_SENSOR
void EspServer::handle_binary_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_binary_sensors()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      bool detail_all = false;
      auto *param = request->getParam("detail");
      if (param != nullptr && param->value() == "all")
        detail_all = true;
      auto json = this->binary_sensor_json_(obj, obj->state, detail_all);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_TEXT_SENSOR
void EspServer::handle_text_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_text_sensors()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      bool detail_all = false;
      auto *param = request->getParam("detail");
      if (param != nullptr && param->value() == "all")
        detail_all = true;
      auto json = this->text_sensor_json_(obj, obj->state, detail_all);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_BINARY_SENSOR
bool EspServer::on_binary_sensor(binary_sensor::BinarySensor *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 2048) return false;
  this->events_.try_send_nodefer(this->binary_sensor_json_(obj, obj->state, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_LIGHT
bool EspServer::on_light(light::LightState *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 4096) return false;
  this->events_.try_send_nodefer(this->light_json_(obj, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_FAN
bool EspServer::on_fan(fan::Fan *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 4096) return false;
  this->events_.try_send_nodefer(this->fan_json_(obj, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_COVER
bool EspServer::on_cover(cover::Cover *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 4096) return false;
  this->events_.try_send_nodefer(this->cover_json_(obj, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_SENSOR
bool EspServer::on_sensor(sensor::Sensor *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 2048) return false;
  this->events_.try_send_nodefer(this->sensor_json_(obj, obj->state, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_SWITCH
bool EspServer::on_switch(switch_::Switch *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 2048) return false;
  this->events_.try_send_nodefer(this->switch_json_(obj, obj->state, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_BUTTON
bool EspServer::on_button(button::Button *obj) { return true; }
#endif
#ifdef USE_TEXT_SENSOR
bool EspServer::on_text_sensor(text_sensor::TextSensor *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 2048) return false;
  this->events_.try_send_nodefer(this->text_sensor_json_(obj, obj->state, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_CLIMATE
bool EspServer::on_climate(climate::Climate *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 4096) return false;
  this->events_.try_send_nodefer(this->climate_json_(obj, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_NUMBER
bool EspServer::on_number(number::Number *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 2048) return false;
  this->events_.try_send_nodefer(this->number_json_(obj, obj->state, true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_SELECT
bool EspServer::on_select(select::Select *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_.buffered_bytes() > 2048) return false;
  this->events_.try_send_nodefer(this->select_json_(obj, obj->current_option(), true).c_str(), "state", millis());
  return true;
}
#endif
#ifdef USE_DATETIME_DATE
bool EspServer::on_date(datetime::DateEntity *obj) { return true; }
#endif
// Removed duplicate on_select
#ifdef USE_DATETIME_TIME
bool EspServer::on_time(datetime::TimeEntity *obj) { return true; }
#endif
#ifdef USE_DATETIME_DATETIME
bool EspServer::on_datetime(datetime::DateTimeEntity *obj) { return true; }
#endif
#ifdef USE_TEXT
bool EspServer::on_text(text::Text *obj) { return true; }
#endif
#ifdef USE_SELECT
// Duplicate on_select removed
#endif
#ifdef USE_LOCK
bool EspServer::on_lock(lock::Lock *obj) { return true; }
#endif
#ifdef USE_VALVE
bool EspServer::on_valve(valve::Valve *obj) { return true; }
#endif
#ifdef USE_ALARM_CONTROL_PANEL
bool EspServer::on_alarm_control_panel(alarm_control_panel::AlarmControlPanel *obj) { return true; }
#endif
#ifdef USE_EVENT
bool EspServer::on_event(event::Event *obj) { return true; }
#endif
#ifdef USE_UPDATE
bool EspServer::on_update(update::UpdateEntity *obj) { return true; }
#endif

}  // namespace web_server
}  // namespace esphome
