#include "esp_server.h"
#include "esphome/core/log.h"
#include "esphome/components/json/json_util.h"
#include "esphome/core/application.h"
#include "esphome/core/controller_registry.h"
#include "esphome/core/entity_base.h"

#ifdef USE_ESP32
#include <esp_heap_caps.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#endif

#ifdef USE_UDPSERVER
#include "esphome/components/udp_server/udp_server.h"
#endif
#ifdef USE_STORAGE
#include "esphome/components/storage/store.h"
#endif
#ifdef USE_LIGHT
#include "esphome/components/light/light_state.h"
#include "esphome/components/light/light_json_schema.h"
#endif
#ifdef USE_CLIMATE
#include "esphome/components/climate/climate.h"
#endif

// Declare constants in global namespace as they are generated by __init__.py
#if USE_ESP_SERVER_VERSION >= 2
extern const uint8_t ESPHOME_ESP_SERVER_INDEX_HTML[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_INDEX_HTML_SIZE;
#endif

#ifdef USE_ESP_SERVER_CSS_INCLUDE
extern const uint8_t ESPHOME_ESP_SERVER_CSS_INCLUDE[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE;
#endif

#ifdef USE_ESP_SERVER_JS_INCLUDE
extern const uint8_t ESPHOME_ESP_SERVER_JS_INCLUDE[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE;
#endif

namespace esphome {
namespace gsmart_esp_server {

static const char *const TAG = "esp_server";

static bool entity_matches_(EntityBase *obj, StringRef id) {
  if (id == obj->get_name())
    return true;

  char id_buf[128];
  obj->write_object_id_to(id_buf, sizeof(id_buf));
  return id == id_buf;
}

static bool request_detail_all_(WebServerRequest *request) {
  auto *param = request->getParam("detail");
  return param != nullptr && param->value() == "all";
}

static const char *initial_state_event_() {
#if USE_ESP_SERVER_VERSION >= 3
  return "state_detail_all";
#else
  return "state";
#endif
}

static float param_float_(WebServerRequest *request, const char *name) {
  return atof(request->getParam(name)->value().c_str());
}

static void set_entity_json_id_(JsonObject root, EntityBase *obj, const char *domain, bool include_metadata) {
  char id_buf[128];
  obj->get_object_id_to(id_buf);
  root["id"] = std::string(domain) + "-" + std::string(id_buf);
  root["name_id"] = std::string(domain) + "/" + obj->get_name().c_str();

  if (include_metadata) {
    root["domain"] = domain;
    root["name"] = obj->get_name().c_str();
    char icon_buf[64];
    root["icon"] = obj->get_icon_to(icon_buf);
    root["entity_category"] = (int) obj->get_entity_category();
    if (obj->is_disabled_by_default())
      root["is_disabled_by_default"] = true;
  }
}

EspServer *global_esp_server = nullptr;

#ifdef USE_ESP32
static uint32_t diag_heap_free() { return heap_caps_get_free_size(MALLOC_CAP_8BIT); }
static uint32_t diag_heap_largest() { return heap_caps_get_largest_free_block(MALLOC_CAP_8BIT); }
static uint32_t diag_heap_min_free() { return heap_caps_get_minimum_free_size(MALLOC_CAP_8BIT); }
#else
static uint32_t diag_heap_free() { return 0; }
static uint32_t diag_heap_largest() { return 0; }
static uint32_t diag_heap_min_free() { return 0; }
#endif

// Constructor with initialization list
EspServer::EspServer(web_server_base::WebServerBase *base) : base_(base), events_("/esp/events") { 
  global_esp_server = this; 
}

void EspServer::setup() {
  ControllerRegistry::register_controller(this);
  global_esp_server = this;
  this->base_->add_handler(this);

#ifdef USE_ESP32
  this->events_.onConnect([this](::esphome::web_server_idf::AsyncEventSourceClient *client) {
    auto uptime = static_cast<uint32_t>(millis_64() / 1000);
    char buf[128];
    snprintf(buf, sizeof(buf), "{\"title\":\"%s\",\"comment\":\"\",\"ota\":true,\"log\":true,\"lang\":\"en\",\"uptime\":%u}",
             App.get_friendly_name().empty() ? App.get_name().c_str() : App.get_friendly_name().c_str(),
             uptime);
    client->try_send_nodefer(buf, "ping", millis(), 30000);

    // Start throttled synchronization for all entities
    this->begin(this->include_internal_);
  });
  this->base_->add_handler(&this->events_);
#endif
  this->setup_interval();
}

void EspServer::loop() {
#ifdef USE_ESP32
  this->events_.loop();
  this->advance();
#endif
}

void EspServer::setup_interval() {
  this->set_interval(30000, [this]() {
#ifdef USE_ESP32
    const auto clients = this->events_.active_count();
#else
    const auto clients = 0;
#endif
    if (clients == 0)
      return;
#ifdef USE_ESP32
    auto uptime = static_cast<uint32_t>(millis_64() / 1000);
    char ping_buf[128];
    snprintf(ping_buf, sizeof(ping_buf),
             "{\"title\":\"%s\",\"comment\":\"\",\"ota\":true,\"log\":true,\"lang\":\"en\",\"uptime\":%u}",
             App.get_friendly_name().empty() ? App.get_name().c_str() : App.get_friendly_name().c_str(), uptime);
    this->events_send(ping_buf, "ping", millis());
#endif
    ESP_LOGD(TAG, "diag: sse=%zu heap=%" PRIu32 " largest=%" PRIu32 " min=%" PRIu32,
             clients, diag_heap_free(), diag_heap_largest(), diag_heap_min_free());
  });

#ifdef USE_LOGGER
  if (logger::global_logger != nullptr && this->expose_log_) {
    logger::global_logger->add_log_callback(
        this, [](void *self, uint8_t level, const char *tag, const char *message, size_t message_len) {
          static_cast<EspServer *>(self)->on_log(level, tag, message, message_len);
        });
  }
#endif

#ifdef USE_UDPSERVER
  if (udp_server::udpServer != nullptr) {
    udp_server::udpServer->add_on_neighbor_callback([this](udp_server::DeviceItem *deviceItem) {
#ifdef USE_ESP32
      this->events_send(deviceItem->toEventMessage().c_str(), "neighbor");
#endif
    });
    udp_server::udpServer->add_on_control_callback([this](udp_server::PacketControl packet) {
#ifdef USE_ESP32
      this->events_send(udp_server::packetControlToJsonStr(packet).c_str(), "udp_control");
#endif
    });
    udp_server::udpServer->add_on_status_callback([this](udp_server::PacketStatus packet) {
#ifdef USE_ESP32
      this->events_send(udp_server::packetStatusToJsonStr(packet).c_str(), "udp_status");
#endif
    });
    udp_server::udpServer->add_on_identity_callback([this](udp_server::PacketIdentity packet) {
#ifdef USE_ESP32
      this->events_send(udp_server::packetIdentityToJsonStr(packet).c_str(), "udp_identity");
#endif
    });
    udp_server::udpServer->add_on_situation_callback([this](udp_server::PacketSituation packet) {
#ifdef USE_ESP32
      this->events_send(udp_server::packetSituationToJsonStr(packet).c_str(), "udp_situation");
#endif
    });
    udp_server::udpServer->add_on_region_layout_callback([this](udp_server::PacketRegionLayout packet) {
#ifdef USE_ESP32
      this->events_send(udp_server::packetRegionLayoutToJsonStr(packet).c_str(), "udp_region_layout");
#endif
    });
    udp_server::udpServer->add_on_region_intent_callback([this](udp_server::PacketRegionIntent packet) {
#ifdef USE_ESP32
      this->events_send(udp_server::packetRegionIntentToJsonStr(packet).c_str(), "udp_region_intent");
#endif
    });
  }
#endif

#ifdef USE_STORAGE
  if (storage::store != nullptr) {
    storage::store->add_on_situation_change([this]() {
#ifdef USE_ESP32
      this->events_send(storage::store->global->situationToJsonStr().c_str(), "situation");
#endif
    });
  }
#endif
}

void EspServer::dump_config() { ESP_LOGCONFIG(TAG, "EspServer Addon:"); }

float EspServer::get_setup_priority() const { return setup_priority::WIFI - 1.0f; }

#ifdef USE_SENSOR
#endif

bool EspServer::canHandle(WebServerRequest *request) const {
#ifdef USE_ESP32
  char url_buf[WebServerRequest::URL_BUF_SIZE];
  String url = request->url_to(url_buf).c_str();
#else
  auto url = request->url();
#endif
  
  if (url == "/esp") return true;
  if (url.startsWith("/esp/")) return true;
  if (url == "/0.css" || url == "/0.js") return true;

  return false;
}

void EspServer::handleRequest(WebServerRequest *request) {
#ifdef USE_ESP32
  char url_buf[WebServerRequest::URL_BUF_SIZE];
  String url = request->url_to(url_buf).c_str();
#else
  auto url = request->url();
#endif

  if (url == "/esp" || url == "/esp/") {
    this->handle_index_request(request);
    return;
  }

  if (url.startsWith("/esp/")) {
    String sub_url = url.substring(4); // Keep the leading slash: "/switch/..."
    
    if (sub_url == "/events") {
      this->events_.handleRequest(request);
      return;
    }
    
    // Simple segment parser for /domain/id[/method]
    int first_slash = sub_url.indexOf('/', 1);
    if (first_slash != -1) {
      ::esphome::UrlMatch match{};
      match.domain = StringRef(sub_url.c_str() + 1, first_slash - 1);
      
      int second_slash = sub_url.indexOf('/', first_slash + 1);
      if (second_slash != -1) {
        match.id = StringRef(sub_url.c_str() + first_slash + 1, second_slash - first_slash - 1);
        match.method = StringRef(sub_url.c_str() + second_slash + 1, sub_url.length() - second_slash - 1);
      } else {
        match.id = StringRef(sub_url.c_str() + first_slash + 1, sub_url.length() - first_slash - 1);
      }
      match.valid = true;

#define HANDLE_DOMAIN(domain_str, handle_method) \
      if (match.domain == domain_str) { \
        this->handle_method(request, match); \
        return; \
      }

#ifdef USE_SENSOR
      HANDLE_DOMAIN("sensor", handle_sensor_request)
#endif
#ifdef USE_SWITCH
      HANDLE_DOMAIN("switch", handle_switch_request)
#endif
#ifdef USE_BUTTON
      HANDLE_DOMAIN("button", handle_button_request)
#endif
#ifdef USE_BINARY_SENSOR
      HANDLE_DOMAIN("binary_sensor", handle_binary_sensor_request)
#endif
#ifdef USE_FAN
      HANDLE_DOMAIN("fan", handle_fan_request)
#endif
#ifdef USE_LIGHT
      HANDLE_DOMAIN("light", handle_light_request)
#endif
#ifdef USE_TEXT_SENSOR
      HANDLE_DOMAIN("text_sensor", handle_text_sensor_request)
#endif
#ifdef USE_COVER
      HANDLE_DOMAIN("cover", handle_cover_request)
#endif
#ifdef USE_NUMBER
      HANDLE_DOMAIN("number", handle_number_request)
#endif
#ifdef USE_SELECT
      HANDLE_DOMAIN("select", handle_select_request)
#endif
#ifdef USE_LOCK
      HANDLE_DOMAIN("lock", handle_lock_request)
#endif
#ifdef USE_CLIMATE
      HANDLE_DOMAIN("climate", handle_climate_request)
#endif
#undef HANDLE_DOMAIN
    }
  }

  if (url == "/esp/diag") {
    std::string data = json::build_json([this](JsonObject root) {
      root["uptime_ms"] = millis();
#ifdef USE_ESP32
      root["sse_clients"] = this->events_.count();
#endif
      root["heap_free"] = diag_heap_free();
      root["heap_largest"] = diag_heap_largest();
      root["heap_min_free"] = diag_heap_min_free();
    });
    request->send(200, "application/json", data.c_str());
    return;
  }

  if (url == "/esp/close-events") {
    this->close_event_sources("manual /esp/close-events");
    request->send(200, "application/json", "{\"ok\":true}");
    return;
  }

#ifdef USE_ESP_SERVER_CSS_INCLUDE
  if (url == "/0.css") {
#ifdef USE_ESP32
    request->send(request->beginResponse(200, "text/css", ESPHOME_ESP_SERVER_CSS_INCLUDE, ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE));
#else
    request->send(200, "text/css", (const uint8_t*)ESPHOME_ESP_SERVER_CSS_INCLUDE, ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE);
#endif
    return;
  }
#endif

#ifdef USE_ESP_SERVER_JS_INCLUDE
  if (url == "/0.js") {
#ifdef USE_ESP32
    request->send(request->beginResponse(200, "application/javascript", ESPHOME_ESP_SERVER_JS_INCLUDE, ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE));
#else
    request->send(200, "application/javascript", (const uint8_t*)ESPHOME_ESP_SERVER_JS_INCLUDE, ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE);
#endif
    return;
  }
#endif
}

void EspServer::handle_index_request(WebServerRequest *request) {
#if USE_ESP_SERVER_VERSION >= 2
#ifdef USE_ESP32
  request->send(request->beginResponse(200, "text/html", ESPHOME_ESP_SERVER_INDEX_HTML, ESPHOME_ESP_SERVER_INDEX_HTML_SIZE));
#else
  request->send(200, "text/html", (const uint8_t*)ESPHOME_ESP_SERVER_INDEX_HTML, ESPHOME_ESP_SERVER_INDEX_HTML_SIZE);
#endif
#else
  request->send(200, "text/html", "v1 index not implemented in addon");
#endif
}

void EspServer::close_event_sources(const char *reason) {
#ifdef USE_ESP32
  this->events_.close_all(reason);
#endif
}

#ifdef USE_LOGGER
void EspServer::on_log(uint8_t level, const char *tag, const char *message, size_t message_len) {
  (void) level;
  (void) tag;
#ifdef USE_ESP32
  if (this->events_.active_count() == 0)
    return;
  // The ESPHome web UI parses logger color prefixes to split level/tag/message.
  this->events_send(std::string(message, message_len).c_str(), "log", millis());
#endif
}
#endif

#ifdef USE_SENSOR
void EspServer::on_sensor_update(sensor::Sensor *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->sensor_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_BINARY_SENSOR
void EspServer::on_binary_sensor_update(binary_sensor::BinarySensor *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->binary_sensor_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_SWITCH
void EspServer::on_switch_update(switch_::Switch *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->switch_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_TEXT_SENSOR
void EspServer::on_text_sensor_update(text_sensor::TextSensor *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->text_sensor_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_LIGHT
void EspServer::on_light_update(light::LightState *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->light_json_(obj).c_str(), "state", millis());
}
#endif
#ifdef USE_FAN
void EspServer::on_fan_update(fan::Fan *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->fan_json_(obj).c_str(), "state", millis());
}
#endif
#ifdef USE_COVER
void EspServer::on_cover_update(cover::Cover *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->cover_json_(obj).c_str(), "state", millis());
}
#endif
#ifdef USE_NUMBER
void EspServer::on_number_update(number::Number *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->number_json_(obj, obj->state).c_str(), "state", millis());
}
#endif
#ifdef USE_SELECT
void EspServer::on_select_update(select::Select *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->select_json_(obj, obj->current_option()).c_str(), "state", millis());
}
#endif
#ifdef USE_CLIMATE
void EspServer::on_climate_update(climate::Climate *obj) {
  if (this->events_.count() == 0) return;
  this->events_send(this->climate_json_(obj).c_str(), "state", millis());
}
#endif

#ifdef USE_BUTTON
void EspServer::handle_button_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_buttons()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method == "press" || match.method == "press ")
        obj->press();
      else if (!match.method.empty()) {
        request->send(404);
        return;
      }
      auto json = this->button_json_(obj, request_detail_all_(request));
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_FAN
void EspServer::handle_fan_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_fans()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method.empty()) {
        auto json = this->fan_json_(obj, request_detail_all_(request));
        request->send(200, "application/json", json.c_str());
        return;
      }

      auto call = obj->make_call();
      if (match.method == "toggle") call.set_state(!obj->state);
      else if (match.method == "turn_on") call.set_state(true);
      else if (match.method == "turn_off") call.set_state(false);
      else {
        request->send(404);
        return;
      }

      if (request->hasParam("speed_level"))
        call.set_speed(atoi(request->getParam("speed_level")->value().c_str()));
      else if (request->hasParam("speed"))
        call.set_speed(atoi(request->getParam("speed")->value().c_str()));
      if (request->hasParam("oscillation")) {
        auto oscillation = request->getParam("oscillation")->value();
        call.set_oscillating(oscillation == "true" || oscillation == "ON" || oscillation == "1");
      }
      call.perform();
      auto json = this->fan_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_LIGHT
void EspServer::handle_light_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_lights()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method.empty()) {
        auto json = this->light_json_(obj, request_detail_all_(request));
        request->send(200, "application/json", json.c_str());
        return;
      }

      auto call = obj->make_call();
      if (match.method == "toggle") call.set_state(!obj->remote_values.is_on());
      else if (match.method == "turn_on") call.set_state(true);
      else if (match.method == "turn_off") call.set_state(false);
      else {
        request->send(404);
        return;
      }
      
      if (request->hasParam("brightness")) call.set_brightness(param_float_(request, "brightness") / 255.0f);
      if (request->hasParam("color_brightness")) call.set_color_brightness(param_float_(request, "color_brightness") / 255.0f);
      if (request->hasParam("r")) call.set_red(param_float_(request, "r") / 255.0f);
      if (request->hasParam("red")) call.set_red(param_float_(request, "red") / 255.0f);
      if (request->hasParam("g")) call.set_green(param_float_(request, "g") / 255.0f);
      if (request->hasParam("green")) call.set_green(param_float_(request, "green") / 255.0f);
      if (request->hasParam("b")) call.set_blue(param_float_(request, "b") / 255.0f);
      if (request->hasParam("blue")) call.set_blue(param_float_(request, "blue") / 255.0f);
      if (request->hasParam("white_value")) call.set_white(param_float_(request, "white_value") / 255.0f);
      if (request->hasParam("white_brightness")) call.set_white(param_float_(request, "white_brightness") / 255.0f);
      if (request->hasParam("color_temp")) call.set_color_temperature(atof(request->getParam("color_temp")->value().c_str()));
      if (request->hasParam("effect")) call.set_effect(request->getParam("effect")->value().c_str());
      
      call.perform();
      auto json = this->light_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_COVER
void EspServer::handle_cover_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_covers()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method.empty()) {
        auto json = this->cover_json_(obj, request_detail_all_(request));
        request->send(200, "application/json", json.c_str());
        return;
      }

      if (match.method == "open") obj->open();
      else if (match.method == "close") obj->close();
      else if (match.method == "stop") obj->stop();
      else if (match.method == "set" || request->hasParam("pos") || request->hasParam("position")) {
        auto call = obj->make_call();
        if (request->hasParam("pos"))
          call.set_position(atof(request->getParam("pos")->value().c_str()));
        if (request->hasParam("position"))
          call.set_position(atof(request->getParam("position")->value().c_str()));
        if (request->hasParam("tilt"))
          call.set_tilt(atof(request->getParam("tilt")->value().c_str()));
        call.perform();
      } else {
        request->send(404);
        return;
      }
      
      auto json = this->cover_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_NUMBER
void EspServer::handle_number_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_numbers()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method.empty()) {
        auto json = this->number_json_(obj, obj->state, request_detail_all_(request));
        request->send(200, "application/json", json.c_str());
        return;
      }
      if (match.method != "set") {
        request->send(404);
        return;
      }
      if (request->hasParam("value"))
        obj->make_call().set_value(atof(request->getParam("value")->value().c_str())).perform();
      auto json = this->number_json_(obj, obj->state);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_SELECT
void EspServer::handle_select_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_selects()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method.empty()) {
        auto json = this->select_json_(obj, obj->current_option(), request_detail_all_(request));
        request->send(200, "application/json", json.c_str());
        return;
      }
      if (match.method != "set") {
        request->send(404);
        return;
      }
      if (request->hasParam("option"))
        obj->make_call().set_option(request->getParam("option")->value().c_str()).perform();
      auto json = this->select_json_(obj, obj->current_option());
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_LOCK
void EspServer::handle_lock_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_locks()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method.empty()) {
        auto json = this->lock_json_(obj, request_detail_all_(request));
        request->send(200, "application/json", json.c_str());
        return;
      }
      if (match.method == "lock") obj->lock();
      else if (match.method == "unlock") obj->unlock();
      else if (match.method == "open") obj->open();
      else {
        request->send(404);
        return;
      }

      auto json = this->lock_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif
#ifdef USE_CLIMATE
void EspServer::handle_climate_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_climates()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method.empty()) {
        auto json = this->climate_json_(obj, request_detail_all_(request));
        request->send(200, "application/json", json.c_str());
        return;
      }
      if (match.method != "set") {
        request->send(404);
        return;
      }
      auto call = obj->make_call();
      if (request->hasParam("mode")) call.set_mode(request->getParam("mode")->value().c_str());
      if (request->hasParam("target_temperature")) call.set_target_temperature(atof(request->getParam("target_temperature")->value().c_str()));
      if (request->hasParam("fan_mode")) call.set_fan_mode(request->getParam("fan_mode")->value().c_str());
      if (request->hasParam("swing_mode")) call.set_swing_mode(request->getParam("swing_mode")->value().c_str());
      call.perform();

      auto json = this->climate_json_(obj);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_SENSOR
std::string EspServer::sensor_json_(sensor::Sensor *obj, float value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "sensor", include_metadata);
    
    if (include_metadata) {
      if (!obj->get_unit_of_measurement_ref().empty())
        root["uom"] = obj->get_unit_of_measurement_ref();
    }

    if (std::isnan(value)) {
      root["state"] = "NA";
    } else {
      char val_buf[64];
      value_accuracy_to_buf(val_buf, value, obj->get_accuracy_decimals());
      std::string state = std::string(val_buf);
      if (!obj->get_unit_of_measurement_ref().empty())
        state += " " + obj->get_unit_of_measurement_ref();
      root["state"] = state;
    }
    root["value"] = value;
  });
}
#endif

#ifdef USE_BINARY_SENSOR
std::string EspServer::binary_sensor_json_(binary_sensor::BinarySensor *obj, bool value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "binary_sensor", include_metadata);
    root["state"] = value ? "ON" : "OFF";
    root["value"] = value;
  });
}
#endif

#ifdef USE_SWITCH
std::string EspServer::switch_json_(switch_::Switch *obj, bool value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "switch", include_metadata);
    root["state"] = value ? "ON" : "OFF";
    root["value"] = value;
    if (include_metadata && obj->assumed_state())
      root["assumed_state"] = true;
  });
}
#endif

#ifdef USE_LIGHT
std::string EspServer::light_json_(light::LightState *obj, bool include_metadata) {
  return json::build_json([this, obj, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "light", include_metadata);
    const char *state = obj->remote_values.is_on() ? "ON" : "OFF";
    root["state"] = state;
    root["value"] = state;
    light::LightJSONSchema::dump_json(*obj, root);

    if (include_metadata) {
      JsonArray opt = root["effects"].to<JsonArray>();
      opt.add("None");
      for (auto const &option : obj->get_effects()) {
        opt.add(option->get_name());
      }
    }
  });
}
#endif

#ifdef USE_FAN
std::string EspServer::fan_json_(fan::Fan *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "fan", include_metadata);
    root["state"] = obj->state ? "ON" : "OFF";
    root["value"] = obj->state;
    const auto traits = obj->get_traits();
    if (traits.supports_speed()) {
      root["speed"] = (int)obj->speed;
      root["speed_level"] = obj->speed;
      root["speed_count"] = traits.supported_speed_count();
    }
    if (traits.supports_oscillation())
      root["oscillation"] = obj->oscillating;
  });
}
#endif

#ifdef USE_COVER
std::string EspServer::cover_json_(cover::Cover *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "cover", include_metadata);
    root["state"] = obj->is_fully_closed() ? "CLOSED" : "OPEN";
    root["value"] = obj->position;
    char operation_buf[18];
    root["current_operation"] =
        ESPHOME_strncpy_P(operation_buf, (ESPHOME_PGM_P) cover::cover_operation_to_str(obj->current_operation),
                          sizeof(operation_buf) - 1);
    root["position"] = obj->position;
    if (obj->get_traits().get_supports_tilt())
      root["tilt"] = obj->tilt;
  });
}
#endif

#ifdef USE_NUMBER
std::string EspServer::number_json_(number::Number *obj, float value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "number", include_metadata);
    const auto uom_ref = obj->get_unit_of_measurement_ref();
    const int8_t accuracy = step_to_accuracy_decimals(obj->traits.get_step());
    char val_buf[64];
    char state_buf[64];

    if (std::isnan(value)) {
      root["state"] = "NA";
      root["value"] = "NaN";
    } else {
      value_accuracy_to_buf(val_buf, value, accuracy);
      value_accuracy_with_uom_to_buf(state_buf, value, accuracy, uom_ref);
      root["state"] = state_buf;
      root["value"] = val_buf;
    }

    if (include_metadata) {
      value_accuracy_to_buf(val_buf, obj->traits.get_min_value(), accuracy);
      root["min_value"] = val_buf;
      root["min"] = val_buf;
      value_accuracy_to_buf(val_buf, obj->traits.get_max_value(), accuracy);
      root["max_value"] = val_buf;
      root["max"] = val_buf;
      value_accuracy_to_buf(val_buf, obj->traits.get_step(), accuracy);
      root["step"] = val_buf;
      root["mode"] = (int) obj->traits.get_mode();
      if (!uom_ref.empty())
        root["uom"] = uom_ref.c_str();
    }
  });
}
#endif

#ifdef USE_BUTTON
std::string EspServer::button_json_(button::Button *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "button", include_metadata);
  });
}
#endif

#ifdef USE_SELECT
std::string EspServer::select_json_(select::Select *obj, const std::string &value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "select", include_metadata);
    root["state"] = value;
    root["value"] = value;
    if (include_metadata) {
      JsonArray options = root["option"].to<JsonArray>();
      for (auto const &option : obj->traits.get_options()) {
        options.add(option);
      }
      JsonArray legacy_options = root["options"].to<JsonArray>();
      for (auto const &option : obj->traits.get_options()) {
        legacy_options.add(option);
      }
    }
  });
}
#endif

#ifdef USE_TEXT_SENSOR
std::string EspServer::text_sensor_json_(text_sensor::TextSensor *obj, const std::string &value, bool include_metadata) {
  return json::build_json([obj, value, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "text_sensor", include_metadata);
    root["state"] = value;
    root["value"] = value;
  });
}
#endif

#ifdef USE_CLIMATE
std::string EspServer::climate_json_(climate::Climate *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "climate", include_metadata);
    root["state"] = climate::climate_mode_to_string(obj->mode);
    root["mode"] = climate::climate_mode_to_string(obj->mode);
    root["current_temperature"] = obj->current_temperature;
    root["target_temperature"] = obj->target_temperature;
    if (obj->get_traits().get_supports_two_point_target_temperature()) {
      root["target_temperature_low"] = obj->target_temperature_low;
      root["target_temperature_high"] = obj->target_temperature_high;
    }
    if (obj->get_traits().get_supports_fan_modes())
      root["fan_mode"] = climate::climate_fan_mode_to_string(obj->fan_mode);
    if (obj->get_traits().get_supports_swing_modes())
      root["swing_mode"] = climate::climate_swing_mode_to_string(obj->swing_mode);
    if (obj->get_traits().get_supports_presets())
      root["preset"] = climate::climate_preset_to_string(obj->preset.value_or(climate::CLIMATE_PRESET_NONE));
    if (obj->get_traits().get_supports_action())
      root["action"] = climate::climate_action_to_string(obj->action);

    if (include_metadata) {
      auto traits = obj->get_traits();
      JsonArray modes = root.createNestedArray("modes");
      for (auto mode : traits.get_supported_modes())
        modes.add(climate::climate_mode_to_string(mode));
      
      if (traits.get_supports_fan_modes()) {
        JsonArray fan_modes = root.createNestedArray("fan_modes");
        for (auto fan_mode : traits.get_supported_fan_modes())
          fan_modes.add(climate::climate_fan_mode_to_string(fan_mode));
      }
      if (traits.get_supports_swing_modes()) {
        JsonArray swing_modes = root.createNestedArray("swing_modes");
        for (auto swing_mode : traits.get_supported_swing_modes())
          swing_modes.add(climate::climate_swing_mode_to_string(swing_mode));
      }
    }
  });
}
#endif

#ifdef USE_LOCK
std::string EspServer::lock_json_(lock::Lock *obj, bool include_metadata) {
  return json::build_json([obj, include_metadata](JsonObject root) {
    set_entity_json_id_(root, obj, "lock", include_metadata);
    root["state"] = lock::lock_state_to_string(obj->state);
  });
}
#endif

#ifdef USE_SENSOR
void EspServer::handle_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_sensors()) {
    if (entity_matches_(obj, match.id)) {
      bool detail_all = request_detail_all_(request);
      auto json = this->sensor_json_(obj, obj->state, detail_all);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_SWITCH
void EspServer::handle_switch_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_switches()) {
    if (entity_matches_(obj, match.id)) {
      if (match.method.empty()) {
        auto json = this->switch_json_(obj, obj->state, request_detail_all_(request));
        request->send(200, "application/json", json.c_str());
        return;
      }
      if (match.method == "toggle") obj->toggle();
      else if (match.method == "turn_on") obj->turn_on();
      else if (match.method == "turn_off") obj->turn_off();
      else {
        request->send(404);
        return;
      }
      
      auto json = this->switch_json_(obj, obj->state);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_BINARY_SENSOR
void EspServer::handle_binary_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_binary_sensors()) {
    if (entity_matches_(obj, match.id)) {
      bool detail_all = request_detail_all_(request);
      auto json = this->binary_sensor_json_(obj, obj->state, detail_all);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_TEXT_SENSOR
void EspServer::handle_text_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_text_sensors()) {
    if (entity_matches_(obj, match.id)) {
      bool detail_all = request_detail_all_(request);
      auto json = this->text_sensor_json_(obj, obj->state, detail_all);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_BINARY_SENSOR
bool EspServer::on_binary_sensor(binary_sensor::BinarySensor *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 2048) return false;
  this->events_send(this->binary_sensor_json_(obj, obj->state, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_LIGHT
bool EspServer::on_light(light::LightState *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 4096) return false;
  this->events_send(this->light_json_(obj, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_FAN
bool EspServer::on_fan(fan::Fan *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 4096) return false;
  this->events_send(this->fan_json_(obj, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_COVER
bool EspServer::on_cover(cover::Cover *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 4096) return false;
  this->events_send(this->cover_json_(obj, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_SENSOR
bool EspServer::on_sensor(sensor::Sensor *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 2048) return false;
  this->events_send(this->sensor_json_(obj, obj->state, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_SWITCH
bool EspServer::on_switch(switch_::Switch *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 2048) return false;
  this->events_send(this->switch_json_(obj, obj->state, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_BUTTON
bool EspServer::on_button(button::Button *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 2048) return false;
  this->events_send(this->button_json_(obj, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_TEXT_SENSOR
bool EspServer::on_text_sensor(text_sensor::TextSensor *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 2048) return false;
  this->events_send(this->text_sensor_json_(obj, obj->state, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_CLIMATE
bool EspServer::on_climate(climate::Climate *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 4096) return false;
  this->events_send(this->climate_json_(obj, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_NUMBER
bool EspServer::on_number(number::Number *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 2048) return false;
  this->events_send(this->number_json_(obj, obj->state, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_SELECT
bool EspServer::on_select(select::Select *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 2048) return false;
  this->events_send(this->select_json_(obj, obj->current_option(), true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_DATETIME_DATE
bool EspServer::on_date(datetime::DateEntity *obj) { return true; }
#endif
// Removed duplicate on_select
#ifdef USE_DATETIME_TIME
bool EspServer::on_time(datetime::TimeEntity *obj) { return true; }
#endif
#ifdef USE_DATETIME_DATETIME
bool EspServer::on_datetime(datetime::DateTimeEntity *obj) { return true; }
#endif
#ifdef USE_TEXT
bool EspServer::on_text(text::Text *obj) { return true; }
#endif
#ifdef USE_SELECT
// Duplicate on_select removed
#endif
#ifdef USE_LOCK
bool EspServer::on_lock(lock::Lock *obj) {
  if (this->events_.count() == 0) return true;
  if (this->events_buffered_bytes() > 2048) return false;
  this->events_send(this->lock_json_(obj, true).c_str(), initial_state_event_(), millis());
  return true;
}
#endif
#ifdef USE_VALVE
bool EspServer::on_valve(valve::Valve *obj) { return true; }
#endif
#ifdef USE_ALARM_CONTROL_PANEL
bool EspServer::on_alarm_control_panel(alarm_control_panel::AlarmControlPanel *obj) { return true; }
#endif
#ifdef USE_EVENT
bool EspServer::on_event(event::Event *obj) { return true; }
#endif
#ifdef USE_UPDATE
bool EspServer::on_update(update::UpdateEntity *obj) { return true; }
#endif

void EspServer::events_send(const char *message, const char *event, uint32_t id) {
#ifdef USE_ESP32
  this->events_.try_send_nodefer(message, event, id);
#else
  this->events_.send(message, event, id);
#endif
}

size_t EspServer::events_buffered_bytes() {
#ifdef USE_ESP32
  return this->events_.buffered_bytes();
#else
  return 0;
#endif
}

}  // namespace gsmart_esp_server
}  // namespace esphome
