#include "esp_server.h"
#include "esphome/core/log.h"
#include "esphome/components/json/json_util.h"
#include "esphome/core/application.h"
#include "esphome/core/controller_registry.h"

#ifdef USE_ESP32
#include <esp_heap_caps.h>
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#endif

#ifdef USE_UDPSERVER
#include "esphome/components/udp_server/udp_server.h"
#endif
#ifdef USE_STORAGE
#include "esphome/components/storage/store.h"
#endif

// Declare constants in global namespace as they are generated by __init__.py
#if USE_ESP_SERVER_VERSION >= 2
extern const uint8_t ESPHOME_ESP_SERVER_INDEX_HTML[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_INDEX_HTML_SIZE;
#endif

#ifdef USE_ESP_SERVER_CSS_INCLUDE
extern const uint8_t ESPHOME_ESP_SERVER_CSS_INCLUDE[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE;
#endif

#ifdef USE_ESP_SERVER_JS_INCLUDE
extern const uint8_t ESPHOME_ESP_SERVER_JS_INCLUDE[] PROGMEM;
extern const size_t ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE;
#endif

namespace esphome {
namespace web_server {

static const char *const TAG = "esp_server";

EspServer *global_esp_server = nullptr;

#ifdef USE_ESP32
static uint32_t diag_heap_free() { return heap_caps_get_free_size(MALLOC_CAP_8BIT); }
static uint32_t diag_heap_largest() { return heap_caps_get_largest_free_block(MALLOC_CAP_8BIT); }
static uint32_t diag_heap_min_free() { return heap_caps_get_minimum_free_size(MALLOC_CAP_8BIT); }
#else
static uint32_t diag_heap_free() { return 0; }
static uint32_t diag_heap_largest() { return 0; }
static uint32_t diag_heap_min_free() { return 0; }
#endif

// Constructor with initialization list
#ifdef USE_ESP32
EspServer::EspServer(web_server_base::WebServerBase *base) : base_(base), events_("/esp/events") { 
  global_esp_server = this; 
}
#else
EspServer::EspServer(web_server_base::WebServerBase *base) : base_(base) { 
}
#endif

void EspServer::setup() {
  ControllerRegistry::register_controller(this);
  global_esp_server = this;
  this->base_->add_handler(this);

#ifdef USE_ESP32
  this->events_.onConnect([this](::esphome::web_server_idf::AsyncEventSourceClient *client) {
    auto uptime = static_cast<uint32_t>(millis_64() / 1000);
    char buf[128];
    snprintf(buf, sizeof(buf), "{\"title\":\"%s\",\"comment\":\"\",\"ota\":true,\"log\":true,\"lang\":\"en\",\"uptime\":%u}",
             App.get_friendly_name().empty() ? App.get_name().c_str() : App.get_friendly_name().c_str(),
             uptime);
    client->try_send_nodefer(buf, "ping", millis(), 30000);

    // Send initial states for all entities
#ifdef USE_SENSOR
    for (auto *obj : App.get_sensors()) {
      if (!this->include_internal_ && obj->is_internal()) continue;
      auto json = this->sensor_json_(obj, obj->state);
      client->try_send_nodefer(json.c_str(), "state");
    }
#endif
#ifdef USE_BINARY_SENSOR
    for (auto *obj : App.get_binary_sensors()) {
      if (!this->include_internal_ && obj->is_internal()) continue;
      auto json = this->binary_sensor_json_(obj, obj->state);
      client->try_send_nodefer(json.c_str(), "state");
    }
#endif
#ifdef USE_SWITCH
    for (auto *obj : App.get_switches()) {
      if (!this->include_internal_ && obj->is_internal()) continue;
      auto json = this->switch_json_(obj, obj->state);
      client->try_send_nodefer(json.c_str(), "state");
    }
#endif
#ifdef USE_TEXT_SENSOR
    for (auto *obj : App.get_text_sensors()) {
      if (!this->include_internal_ && obj->is_internal()) continue;
      auto json = this->text_sensor_json_(obj, obj->state);
      client->try_send_nodefer(json.c_str(), "state");
    }
#endif
  });
  this->base_->add_handler(&this->events_);
#endif
  this->setup_interval();
}

void EspServer::loop() {
#ifdef USE_ESP32
  this->events_.loop();
#endif
}

void EspServer::setup_interval() {
  this->set_interval(30000, [this]() {
#ifdef USE_ESP32
    const auto clients = this->events_.count();
#else
    const auto clients = 0;
#endif
    if (clients == 0)
      return;
    ESP_LOGD(TAG, "diag: sse=%zu heap=%" PRIu32 " largest=%" PRIu32 " min=%" PRIu32,
             clients, diag_heap_free(), diag_heap_largest(), diag_heap_min_free());
  });

#ifdef USE_LOGGER
  if (logger::global_logger != nullptr && this->expose_log_) {
    logger::global_logger->add_log_callback(
        this, [](void *self, uint8_t level, const char *tag, const char *message, size_t message_len) {
          static_cast<EspServer *>(self)->on_log(level, tag, message, message_len);
        });
  }
#endif

#ifdef USE_UDPSERVER
  if (udp_server::udpServer != nullptr) {
    udp_server::udpServer->add_on_neighbor_callback([this](udp_server::DeviceItem *deviceItem) {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(deviceItem->toEventMessage().c_str(), "neighbor");
#endif
    });
    udp_server::udpServer->add_on_control_callback([this](udp_server::PacketControl packet) {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(udp_server::packetControlToJsonStr(packet).c_str(), "udp_control");
#endif
    });
    udp_server::udpServer->add_on_status_callback([this](udp_server::PacketStatus packet) {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(udp_server::packetStatusToJsonStr(packet).c_str(), "udp_status");
#endif
    });
    udp_server::udpServer->add_on_identity_callback([this](udp_server::PacketIdentity packet) {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(udp_server::packetIdentityToJsonStr(packet).c_str(), "udp_identity");
#endif
    });
  }
#endif

#ifdef USE_STORAGE
  if (storage::store != nullptr) {
    storage::store->add_on_situation_change([this]() {
#ifdef USE_ESP32
      this->events_.try_send_nodefer(storage::store->global->situationToJsonStr().c_str(), "situation");
#endif
    });
  }
#endif
}

void EspServer::dump_config() { ESP_LOGCONFIG(TAG, "EspServer Addon:"); }

float EspServer::get_setup_priority() const { return setup_priority::WIFI - 1.0f; }

#ifdef USE_SENSOR
void EspServer::on_sensor_update(sensor::Sensor *obj) {
  if (!this->include_internal_ && obj->is_internal()) return;
  auto json = this->sensor_json_(obj, obj->state);
  this->events_.try_send_nodefer(json.c_str(), "state");
}
#endif

#ifdef USE_BINARY_SENSOR
void EspServer::on_binary_sensor_update(binary_sensor::BinarySensor *obj) {
  if (!this->include_internal_ && obj->is_internal()) return;
  auto json = this->binary_sensor_json_(obj, obj->state);
  this->events_.try_send_nodefer(json.c_str(), "state");
}
#endif

#ifdef USE_SWITCH
void EspServer::on_switch_update(switch_::Switch *obj) {
  if (!this->include_internal_ && obj->is_internal()) return;
  auto json = this->switch_json_(obj, obj->state);
  this->events_.try_send_nodefer(json.c_str(), "state");
}
#endif

#ifdef USE_LIGHT
void EspServer::on_light_update(light::LightState *obj) {
  // this->events_.deferrable_send_state(obj, "state", WebServer::light_state_json_generator);
}
#endif

#ifdef USE_FAN
void EspServer::on_fan_update(fan::Fan *obj) {
  this->events_.deferrable_send_state(obj, "state", WebServer::fan_state_json_generator);
}
#endif

#ifdef USE_COVER
void EspServer::on_cover_update(cover::Cover *obj) {
  this->events_.deferrable_send_state(obj, "state", WebServer::cover_state_json_generator);
}
#endif

#ifdef USE_TEXT_SENSOR
void EspServer::on_text_sensor_update(text_sensor::TextSensor *obj) {
  if (!this->include_internal_ && obj->is_internal()) return;
  auto json = this->text_sensor_json_(obj, obj->state);
  this->events_.try_send_nodefer(json.c_str(), "state");
}
#endif

#ifdef USE_NUMBER
void EspServer::on_number_update(number::Number *obj) {
  // this->events_.deferrable_send_state(obj, "state", WebServer::number_state_json_generator);
}
#endif

#ifdef USE_SELECT
void EspServer::on_select_update(select::Select *obj) {
  // this->events_.deferrable_send_state(obj, "state", WebServer::select_state_json_generator);
}
#endif

#ifdef USE_LOCK
void EspServer::on_lock_update(lock::Lock *obj) {
  this->events_.deferrable_send_state(obj, "state", WebServer::lock_state_json_generator);
}
#endif

bool EspServer::canHandle(WebServerRequest *request) const {
#ifdef USE_ESP32
  char url_buf[WebServerRequest::URL_BUF_SIZE];
  String url = request->url_to(url_buf).c_str();
#else
  auto url = request->url();
#endif
  
  if (url == "/esp") return true;
  if (url.startsWith("/esp/")) return true;
  if (url == "/0.css" || url == "/0.js") return true;

  return false;
}

void EspServer::handleRequest(WebServerRequest *request) {
#ifdef USE_ESP32
  char url_buf[WebServerRequest::URL_BUF_SIZE];
  String url = request->url_to(url_buf).c_str();
#else
  auto url = request->url();
#endif

  if (url == "/esp" || url == "/esp/") {
    this->handle_index_request(request);
    return;
  }

  if (url.startsWith("/esp/")) {
    String sub_url = url.substring(4); // Keep the leading slash: "/switch/..."
    
    if (sub_url == "/events") {
      this->events_.handleRequest(request);
      return;
    }
    
    // Simple segment parser for /domain/id[/method]
    int first_slash = sub_url.indexOf('/', 1);
    if (first_slash != -1) {
      ::esphome::UrlMatch match{};
      match.domain = StringRef(sub_url.c_str() + 1, first_slash - 1);
      
      int second_slash = sub_url.indexOf('/', first_slash + 1);
      if (second_slash != -1) {
        match.id = StringRef(sub_url.c_str() + first_slash + 1, second_slash - first_slash - 1);
        match.method = StringRef(sub_url.c_str() + second_slash + 1, sub_url.length() - second_slash - 1);
      } else {
        match.id = StringRef(sub_url.c_str() + first_slash + 1, sub_url.length() - first_slash - 1);
      }
      match.valid = true;

#define HANDLE_DOMAIN(domain_str, handle_method) \
      if (match.domain == domain_str) { \
        this->handle_method(request, match); \
        return; \
      }

#ifdef USE_SENSOR
      HANDLE_DOMAIN("sensor", handle_sensor_request)
#endif
#ifdef USE_SWITCH
      HANDLE_DOMAIN("switch", handle_switch_request)
#endif
#ifdef USE_BUTTON
      HANDLE_DOMAIN("button", handle_button_request)
#endif
#ifdef USE_BINARY_SENSOR
      HANDLE_DOMAIN("binary_sensor", handle_binary_sensor_request)
#endif
#ifdef USE_FAN
      HANDLE_DOMAIN("fan", handle_fan_request)
#endif
#ifdef USE_LIGHT
      HANDLE_DOMAIN("light", handle_light_request)
#endif
#ifdef USE_TEXT_SENSOR
      HANDLE_DOMAIN("text_sensor", handle_text_sensor_request)
#endif
#ifdef USE_COVER
      HANDLE_DOMAIN("cover", handle_cover_request)
#endif
#ifdef USE_NUMBER
      HANDLE_DOMAIN("number", handle_number_request)
#endif
#ifdef USE_SELECT
      HANDLE_DOMAIN("select", handle_select_request)
#endif
#ifdef USE_LOCK
      HANDLE_DOMAIN("lock", handle_lock_request)
#endif
#ifdef USE_CLIMATE
      HANDLE_DOMAIN("climate", handle_climate_request)
#endif
#undef HANDLE_DOMAIN
    }
  }

  if (url == "/esp/diag") {
    std::string data = json::build_json([this](JsonObject root) {
      root["uptime_ms"] = millis();
#ifdef USE_ESP32
      root["sse_clients"] = this->events_.count();
#endif
      root["heap_free"] = diag_heap_free();
      root["heap_largest"] = diag_heap_largest();
      root["heap_min_free"] = diag_heap_min_free();
    });
    request->send(200, "application/json", data.c_str());
    return;
  }

  if (url == "/esp/close-events") {
    this->close_event_sources("manual /esp/close-events");
    request->send(200, "application/json", "{\"ok\":true}");
    return;
  }

#ifdef USE_ESP_SERVER_CSS_INCLUDE
  if (url == "/0.css") {
#ifdef USE_ESP32
    request->send(request->beginResponse(200, "text/css", ESPHOME_ESP_SERVER_CSS_INCLUDE, ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE));
#else
    request->send(200, "text/css", (const uint8_t*)ESPHOME_ESP_SERVER_CSS_INCLUDE, ESPHOME_ESP_SERVER_CSS_INCLUDE_SIZE);
#endif
    return;
  }
#endif

#ifdef USE_ESP_SERVER_JS_INCLUDE
  if (url == "/0.js") {
#ifdef USE_ESP32
    request->send(request->beginResponse(200, "application/javascript", ESPHOME_ESP_SERVER_JS_INCLUDE, ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE));
#else
    request->send(200, "application/javascript", (const uint8_t*)ESPHOME_ESP_SERVER_JS_INCLUDE, ESPHOME_ESP_SERVER_JS_INCLUDE_SIZE);
#endif
    return;
  }
#endif
}

void EspServer::handle_index_request(WebServerRequest *request) {
#if USE_ESP_SERVER_VERSION >= 2
#ifdef USE_ESP32
  request->send(request->beginResponse(200, "text/html", ESPHOME_ESP_SERVER_INDEX_HTML, ESPHOME_ESP_SERVER_INDEX_HTML_SIZE));
#else
  request->send(200, "text/html", (const uint8_t*)ESPHOME_ESP_SERVER_INDEX_HTML, ESPHOME_ESP_SERVER_INDEX_HTML_SIZE);
#endif
#else
  request->send(200, "text/html", "v1 index not implemented in addon");
#endif
}

void EspServer::close_event_sources(const char *reason) {
  this->events_.close_all(reason);
}

#ifdef USE_LOGGER
void EspServer::on_log(uint8_t level, const char *tag, const char *message, size_t message_len) {
#ifdef USE_ESP32
  if (this->events_.count() == 0)
    return;
  std::string data = json::build_json([&](JsonObject root) {
    root["level"] = level;
    root["tag"] = tag;
    root["message"] = message;
  });
  this->events_.try_send_nodefer(data.c_str(), "log");
#endif
}
#endif

#ifdef USE_BUTTON
void EspServer::handle_button_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  request->send(404);
}
#endif
#ifdef USE_FAN
void EspServer::handle_fan_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  request->send(404);
}
#endif
#ifdef USE_LIGHT
void EspServer::handle_light_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  request->send(404);
}
#endif
#ifdef USE_COVER
void EspServer::handle_cover_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  request->send(404);
}
#endif
#ifdef USE_NUMBER
void EspServer::handle_number_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  request->send(404);
}
#endif
#ifdef USE_SELECT
void EspServer::handle_select_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  request->send(404);
}
#endif
#ifdef USE_LOCK
void EspServer::handle_lock_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  request->send(404);
}
#endif
#ifdef USE_CLIMATE
void EspServer::handle_climate_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  request->send(404);
}
#endif

#ifdef USE_SENSOR
std::string EspServer::sensor_json_(sensor::Sensor *obj, float value) {
  return json::build_json([obj, value](JsonObject root) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    root["id"] = "sensor-" + std::string(id_buf);
    
    if (std::isnan(value)) {
      root["state"] = "NA";
    } else {
      char val_buf[64];
      value_accuracy_to_buf(val_buf, value, obj->get_accuracy_decimals());
      root["state"] = std::string(val_buf);
    }
    root["value"] = value;
  });
}
#endif

#ifdef USE_BINARY_SENSOR
std::string EspServer::binary_sensor_json_(binary_sensor::BinarySensor *obj, bool value) {
  return json::build_json([obj, value](JsonObject root) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    root["id"] = "binary_sensor-" + std::string(id_buf);
    root["state"] = value ? "ON" : "OFF";
    root["value"] = value;
  });
}
#endif

#ifdef USE_SWITCH
std::string EspServer::switch_json_(switch_::Switch *obj, bool value) {
  return json::build_json([obj, value](JsonObject root) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    root["id"] = "switch-" + std::string(id_buf);
    root["state"] = value ? "ON" : "OFF";
    root["value"] = value;
  });
}
#endif

#ifdef USE_TEXT_SENSOR
std::string EspServer::text_sensor_json_(text_sensor::TextSensor *obj, const std::string &value) {
  return json::build_json([obj, value](JsonObject root) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    root["id"] = "text_sensor-" + std::string(id_buf);
    root["state"] = value;
    root["value"] = value;
  });
}
#endif

#ifdef USE_SENSOR
void EspServer::handle_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_sensors()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      auto json = this->sensor_json_(obj, obj->state);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_SWITCH
void EspServer::handle_switch_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_switches()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      if (match.method == "toggle") obj->toggle();
      else if (match.method == "turn_on") obj->turn_on();
      else if (match.method == "turn_off") obj->turn_off();
      
      auto json = this->switch_json_(obj, obj->state);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_BINARY_SENSOR
void EspServer::handle_binary_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_binary_sensors()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      auto json = this->binary_sensor_json_(obj, obj->state);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

#ifdef USE_TEXT_SENSOR
void EspServer::handle_text_sensor_request(WebServerRequest *request, const ::esphome::UrlMatch &match) {
  for (auto *obj : App.get_text_sensors()) {
    char id_buf[128];
    obj->write_object_id_to(id_buf, sizeof(id_buf));
    if (std::string(id_buf) == match.id.c_str()) {
      auto json = this->text_sensor_json_(obj, obj->state);
      request->send(200, "application/json", json.c_str());
      return;
    }
  }
  request->send(404);
}
#endif

}  // namespace web_server
}  // namespace esphome
